### ISSUE TITLE
Decision Proposal 259 - Maintenance Iteration 12 

### ISSUE THREAD

**Issue by CDR-API-Stream** [ConsumerDataStandardsAustralia/standards#259]
20 July 2022: Consultation open

This decision will capture the consultation of Maintenance Iteration 12. Consultation will commence on the change requests in the standards maintenance repository.

Meeting agendas and minutes will be posted in the comments below. The first call of this maintenance iteration will be held on Wednesday 20/07/2022.

The DSB invites the community to provide any recommendations of change requests to be considered for priority in this iteration.

**Comment by CDR-API-Stream** [comment]
The agenda for today's Maintenance Iteration call is available at https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(20-July-2022)

The DSB is calling for suggestions from the community on issues to include in MI12 for consideration and discussion today.  A retrospective on MI 11 will also be conducted.

The meeting is scheduled to run for 2 hours however we are planning to wrap up by 3:30PM AEST.

**Comment by CDR-API-Stream** [comment]
Meeting notes from the Maintenance Iteration call on 20/07/2022 are available at https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(20-July-2022)#notes

The DSB encourages the community to review the Change Requests (CR) proposed in the section [Maintenance Iteration 12 Issues](https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(20-July-2022)#maintenance-iteration-12-issues-1). You can provide comments on those items you'd like to see prioritised and suggest CRs to include in this iteration by posting on this issue.

**Comment by AusBanking** [comment]
The ABA requests that the DCR response time issue (https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/409) be considered in the context of MI 12

**Comment by CDR-API-Stream** [comment]
We have included 409 in the candidate list

**Comment by CDR-API-Stream** [comment]
The agenda for the Maintenance Iteration meeting on 3 August 2022 is available at https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(3-August-2022)

The change requests proposed for this iteration are:
* [Issue #414 - Properties in BankingTransactionDetail objects](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/414)
* [Issue #525 - softwareProductDescription should be marked as mandatory](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/525)
* [Issue #526 - Get DER for Service Point - allow for no data](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/526)
* [Issue #524 - EnergyDerRecord - mandatory values not available in AEMO's DER register](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/524)
* [Issue #506 - Energy error codes for issues in data received by DH from SDH](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/506)
* [Issue #477 - Secondary Data Holder Planned Outages and Status](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/477)
* [Issue #480 - 1.13.0 appears to have broken pseudonymity of Pairwise Identifiers](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/480)
* [Issue #484 - 1.13.0 Appears to have introduced new SSA error behaviours](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/484)
* [Issue #529 - CX - Energy Data Language Standards - NMI and Scheduled Payments](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/529)
* [Issue #409 - Dynamic Client Registration Response Time NFR](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/409)
* [Issue #411 - Clarification of x-fapi-interaction-id header](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/411)
* [Issue #447 - CORS typos in CDR](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/447)
* [Issue #458 - FAPI 1.0 Non Normative Examples](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/458)
* [Issue #475 - Energy - Representation of Spot price based contracts for C&I customers](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/475)
* [Issue #520 - Stepped solar feed in tariffs in Energy](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/520)
* [Issue #435 - Nominated representative end user for non-individual consumers](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/435)
* [Issue #462 - Make additional account attributes available in bulk](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/462)
* [Issue #530 - Iteration 12 Holistic Feedback](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/530)

**Comment by CDR-API-Stream** [comment]
The meeting minutes for yesterday's Maintenance Iteration call have been published: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(3-August-2022)

The list of change requests proposed above were confirmed. The scope of the iteration was increased to include two additional change requests:

* [Issue #479 - Clarification on Minimum Algorithm Required for JARM](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/479)
* [Issue #522 - OpenID Provider Configuration End Point parameter requirements](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/522)

**Comment by CDR-API-Stream** [comment]
The Maintenance Iteration call Agenda for 17/08/2022 has been published: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(17-August-2022)

The change requests proposed for this iteration are:

**CX**
* [Issue #529 - CX - Energy Data Language Standards - NMI and Scheduled Payments](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/529)

**Energy**
* [Issue #475 - Energy - Representation of Spot price based contracts for C&I customers](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/475)
* [Issue #477 - Secondary Data Holder Planned Outages and Status](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/477)
* [Issue #506 - Energy error codes for issues in data received by DH from SDH](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/506)
* [Issue #524 - EnergyDerRecord - mandatory values not available in AEMO's DER register](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/524)
* [Issue #520 - Stepped solar feed in tariffs in Energy](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/520)
* [Issue #526 - Get DER for Service Point - allow for no data](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/526)

**Banking**
* [Issue #414 - Properties in BankingTransactionDetail objects](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/414)
* [Issue #462 - Make additional account attributes available in bulk](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/462)

**InfoSec**
* [Issue #411 - Clarification of x-fapi-interaction-id header](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/411)
* [Issue #435 - Nominated representative end user for non-individual consumers](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/435)
* [Issue #447 - CORS typos in CDR](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/447)
* [Issue #458 - FAPI 1.0 Non Normative Examples](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/458)
* [Issue #479 - Clarification on Minimum Algorithm Required for JARM](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/479) 
* [Issue #522 - OpenID Provider Configuration End Point parameter requirements](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/522)

**Register**
* [Issue #409 - Dynamic Client Registration Response Time NFR](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/409)
* [Issue #525 - softwareProductDescription should be marked as mandatory](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/525)

**MI 12**
* [Issue #530 - Iteration 12 Holistic Feedback](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/530)

**Comment by CDR-API-Stream** [comment]
The meeting minutes for last week's Maintenance Iteration call have been published: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(17-August-2022)#meeting-minutes

**Comment by CDR-API-Stream** [comment]
Please note a correction has been made to the minutes, the following were new actions arising on 17 August.
* [ ] Consensus from Energy Retailers is required to mark [Issue #506 - Energy error codes for issues in data received by DH from SDH](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/506) as urgent. 
* [ ] Consensus from Energy Retailers is required to mark [Issue #524 - EnergyDerRecord - mandatory values not available in AEMO's DER register](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/524) as urgent.
* [ ] Consensus from Energy Retailers is required to mark [Issue #526 - Get DER for Service Point - allow for no data](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/526) as urgent. 

A consensus to the Change Requests listed above, and [Issue #529 - CX - Energy Data Language Standards - NMI and Scheduled Payments](https://github.com/ConsumerDataStandardsAustralia/standards-maintenance/issues/529) applies to all Energy Retailers with an obligation date of 15 November 2022.

**Comment by CDR-API-Stream** [comment]
Meeting minutes for yesterday's maintenance iteration call are available here: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(31-August-2022)

The final call for this maintenance iteration will be held on 14/11/2022 at 2pm AEST.

**Comment by CDR-API-Stream** [comment]
The meeting agenda for tomorrow's Maintenance Iteration call is available here: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(14-September-2022).

This is the final call for Maintenance Iteration 12 and will be held on 14/09/2022 at 2pm AEST.

**Comment by CDR-API-Stream** [comment]
Meeting minutes for the call held on 14/09/2022 have been published: https://github.com/ConsumerDataStandardsAustralia/standards/wiki/DSB-Maintenance-Iteration-12:-Agenda-&-Minutes-(14-September-2022)#meeting-minutes

**Comment by CDR-API-Stream** [comment]
The Chair has made a decision in regard to this consultation.  The decision paper is attached below:
[Decision 259 - Maintenance Iteration 12.pdf](https://github.com/ConsumerDataStandardsAustralia/standards/files/9925787/Decision.259.-.Maintenance.Iteration.12.pdf)
